### ISSUE TITLE
year in column head

### ISSUE THREAD

**Issue by arlocsherman** [CenterOnBudget/getcensus#15]
Do column headings for income values always say they're "in 2017 dollars" regardless of the data year? Noticing this for b19013 (median income).  Presumably that's not accurate (i.e., every year of ACS data is simply "inflation adjusted" to its own calendar year, as opposed to a mix of the current and prior year)?  If pulling a correct year-specific title for every year is difficult, is it easier to strip out the year?

**Comment by c-zippel** [comment]
Does that make sense? If so I will close out this issue.

**Comment by arlocsherman** [comment]
Hmm.  When I type, say, "getcensus b19013b_001, clear year(2016)", or "..year(2018)" or any other year, I still get b19013b_001e labeled as "Estimate!!Median household income in the past 12 months (in 2017 inflation-adjus".  I might have an outdated version of getcensus, though.

**Comment by c-zippel** [comment]
Ditto on the hmm. I will take a look.

**Comment by c-zippel** [comment]
Okay, this is partially a bug and partially a design issue. 

  1. The section of the code that sets the data dictionary year based on the data year was not operational because 2017 was hard-coded as the data dictionary year on line 777. This could have been done for debugging or as a temporary patch for problem 2 below.  Hence 2017 appearing regardless of the data year. This is the bug, and is easy to fix _for users pulling one year of data._  

  1. There's a larger design flaw in pulling the data dictionary based on the data year when a user is pulling _multiple years of data_. Of course, variables can only have one label. I think the solution is for `getcensus` to choose one year from series the user requested and pull the data dictionary for that year -- I would suggest using the last year in the series. But, for variable labels that are specific to the data year -- i.e. "in 20XX inflation-adjusted dollars", the label won't be accurate for all years of data, as you pointed out at the top of this thread. In those cases, `getcensus` could edit those labels to remove "in 20XX inflation-adjusted dollars" or replace it with something like "in nominal dollars" (although the latter might be confusing for 5-year data...).

Questions for you:
- Preferences/recommendations on how to address problem 2? 
- Level of priority for this issue?

**Comment by arlocsherman** [comment]
Is there an easy fix for now such as leaving 2017 in line 777 and replacing “in 2017 inflation-adjusted dollars” with “in nominal dollars”?

I could see this being worth at least a temporary fix in the next 2 weeks because of the danger that a state group would treat a time series as inflation-adjusted.

**Comment by c-zippel** [comment]
Makes sense. I will do that this week.

**Comment by c-zippel** [comment]
Let's default to 2018 (the latest year available) rather than 2017?
If you agree, we're very close to a fix. I've submitted a pull request for Matt to QA.
